openapi: 3.0.0
info:
  title: Swift API
  version: 1.0.0
  description: API for accepting and storing MT799 messages
servers:
  - url: http://localhost:3000/
paths:
  /messages:
    post:
      summary: Upload a new MT799 message file
      operationId: uploadMessage
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: MT799 message uploaded and saved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID of the saved message
        '400':
          description: Bad Request, file not provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    get:
      summary: Retrieve a list of all MT799 messages
      operationId: getMessages
      responses:
        '200':
          description: A list of MT799 messages
          content:
            text/html:
              schema:
                type: string
    delete:
      summary: Delete a specific MT799 message by ID
      operationId: deleteMessage
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the MT799 message to delete
      responses:
        '200':
          description: MT799 message deleted successfully
        '404':
          description: MT799 message not found
        '500':
          description: Internal Server Error
